version: "3"
services:
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    volumes:
      - ./:/ror
    ports:
      - "3100:3000"
    depends_on:
      - database
      - redis
    environment:
      - POSTGRES_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - SOLID_QUEUE_ADAPTER=redis
      
volumes:
  postgres_db: