version: "3"
services:
  solid_queue:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rake solid_queue:start
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres@database
    volumes:
      - .:/usr/src/app
      
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/walltaker_database2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    volumes:
      - ./:/ror
    ports:
      - "3100:3000"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
